"use client";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowUpRight, Banknote, Flame, MessageCircle, MoreHorizontal, ShoppingBag, Sparkles, TrendingUp, UserRoundPlus } from "lucide-react";
const chart=[{day:"Lun",conversations:88,ventes:8},{day:"Mar",conversations:105,ventes:11},{day:"Mer",conversations:98,ventes:9},{day:"Jeu",conversations:136,ventes:17},{day:"Ven",conversations:149,ventes:21},{day:"Sam",conversations:122,ventes:15},{day:"Dim",conversations:168,ventes:24}];
const objections=[{name:"Prix",value:38,color:"#316ddd"},{name:"Besoin de réfléchir",value:26,color:"#6da0ff"},{name:"Confiance",value:18,color:"#58c49c"},{name:"Timing",value:12,color:"#f2b64b"},{name:"Autres",value:6,color:"#c8d1de"}];
const hot=[{name:"Jean Koffi",initials:"JK",score:92,status:"Très chaud",intention:"Achat",objection:"Prix",time:"Il y a 5 min"},{name:"Fatou Ndiaye",initials:"FN",score:86,status:"Très chaud",intention:"Achat",objection:"Confiance",time:"Il y a 12 min"},{name:"Oumar Sawadogo",initials:"OS",score:79,status:"Chaud",intention:"Comparaison",objection:"Timing",time:"Il y a 21 min"},{name:"Sarah Dubois",initials:"SD",score:75,status:"Chaud",intention:"Information",objection:"Prix",time:"Il y a 34 min"}];
export default function DashboardPage(){return <>
 <div className="page-head"><div><h2>Bonjour Aïcha, <span className="wave-hello">👋</span></h2><p>Voici ce qui se passe dans votre activité aujourd’hui.</p></div><button className="btn btn-primary"><Sparkles size={16}/> Voir les opportunités</button></div>
 <div className="stats-grid"><Stat icon={<MessageCircle/>} label="Conversations aujourd’hui" value="148" trend="+18%" bg="#eaf1ff" color="#2b66d7"/><Stat icon={<Flame/>} label="Prospects chauds" value="24" trend="+8 aujourd’hui" bg="#fff1e8" color="#ec732b"/><Stat icon={<ShoppingBag/>} label="Ventes" value="16" trend="+12,5%" bg="#e9f8f1" color="#0b9669"/><Stat icon={<Banknote/>} label="Chiffre d’affaires" value="8 420 €" trend="+24,2%" bg="#f1edff" color="#7454d6"/></div>
 <div className="grid-2"><section className="card panel"><div className="panel-head"><div><h3>Conversations & conversions</h3><p className="small muted">Activité des 7 derniers jours</p></div><select className="mini-select"><option>7 derniers jours</option><option>30 derniers jours</option></select></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{top:8,right:10,left:-23,bottom:0}}><defs><linearGradient id="convFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3b76e5" stopOpacity={.25}/><stop offset="100%" stopColor="#3b76e5" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fill:"#8995a7",fontSize:11}}/><YAxis axisLine={false} tickLine={false} tick={{fill:"#8995a7",fontSize:10}}/><Tooltip contentStyle={{border:"1px solid #e4e8ef",borderRadius:11,boxShadow:"0 10px 30px rgba(20,40,80,.1)",fontSize:11}}/><Area type="monotone" dataKey="conversations" stroke="#3470df" fill="url(#convFill)" strokeWidth={3}/><Area type="monotone" dataKey="ventes" stroke="#27b281" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div><div className="chart-legend"><span><i style={{background:"#3470df"}}/>Conversations</span><span><i style={{background:"#27b281"}}/>Ventes</span></div></section>
 <section className="card panel"><div className="panel-head"><div><h3>Objections fréquentes</h3><p className="small muted">Sur 126 objections détectées</p></div><button className="icon-btn"><MoreHorizontal size={17}/></button></div><div className="donut-wrap"><ResponsiveContainer width="55%" height={190}><PieChart><Pie data={objections} innerRadius={52} outerRadius={72} dataKey="value" paddingAngle={3}>{objections.map(o=><Cell fill={o.color} key={o.name}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="donut-center"><b>126</b><span>objections</span></div><div className="donut-legend">{objections.map(o=><span key={o.name}><i style={{background:o.color}}/><em>{o.name}</em><b>{o.value}%</b></span>)}</div></div></section></div>
 <section className="card panel hot-panel"><div className="panel-head"><div><h3><Flame size={17}/> Prospects chauds</h3><p className="small muted">Conversations à fort potentiel de conversion</p></div><button className="btn btn-secondary btn-sm">Voir tous <ArrowUpRight size={14}/></button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Prospect</th><th>Score</th><th>Statut</th><th>Intention</th><th>Objection</th><th>Dernière activité</th><th></th></tr></thead><tbody>{hot.map(p=><tr key={p.name}><td><div className="contact-cell"><span className="contact-avatar">{p.initials}</span>{p.name}</div></td><td><span className="score">{p.score}</span></td><td><span className={p.score>80?"badge badge-red":"badge badge-amber"}>{p.status}</span></td><td>{p.intention}</td><td><span className="objection-pill">{p.objection}</span></td><td className="muted">{p.time}</td><td><button className="icon-btn"><ArrowUpRight size={15}/></button></td></tr>)}</tbody></table></div></section>
 <div className="dashboard-bottom"><section className="card panel"><div className="panel-head"><h3>Conversations à reprendre</h3><span className="badge badge-red">3 urgentes</span></div><div className="human-list"><Human initials="MB" name="Marc B." reason="Demande de remboursement" time="2 min"/><Human initials="AL" name="Aminata L." reason="Question hors base de connaissances" time="8 min"/><Human initials="PK" name="Paul K." reason="Souhaite parler à un conseiller" time="17 min"/></div></section><section className="card panel ai-insight"><div className="insight-icon"><Sparkles/></div><div><span className="section-kicker">Insight CloseAI</span><h3>Votre meilleure plage de conversion est entre 18h et 21h.</h3><p>32% de vos ventes sont conclues pendant cette période. Activez le mode automatique pour ne manquer aucun prospect.</p><button className="btn btn-secondary btn-sm">Configurer l’automatisation</button></div></section></div>
 </>}
function Stat({icon,label,value,trend,bg,color}:{icon:React.ReactNode;label:string;value:string;trend:string;bg:string;color:string}){return <div className="card stat-card"><div className="stat-head"><span>{label}</span><i className="stat-icon" style={{background:bg,color}}>{icon}</i></div><div className="stat-value">{value}</div><span className="trend"><TrendingUp size={12}/>{trend} <em>vs hier</em></span></div>}
function Human({initials,name,reason,time}:{initials:string;name:string;reason:string;time:string}){return <div className="human-row"><span className="contact-avatar">{initials}</span><div><b>{name}</b><small>{reason}</small></div><time>{time}</time><button className="btn btn-primary btn-sm">Reprendre</button></div>}
