"use client";
import { useState } from "react";
import { Archive, Bot, Check, ChevronDown, Clock3, Copy, Edit3, Image as ImageIcon, Info, MoreHorizontal, Paperclip, Phone, Play, RefreshCw, Search, Send, Sparkles, UserRound, Volume2, WandSparkles, X } from "lucide-react";

type Conversation={id:number;name:string;initials:string;preview:string;time:string;unread?:number;status:string;score:number;country:string;phone:string;product:string;objection:string;color:string};
const conversations:Conversation[]=[
{id:1,name:"Jean Koffi",initials:"JK",preview:"Oui, mais le prix est un peu...",time:"10:42",unread:2,status:"Très chaud",score:92,country:"Côte d’Ivoire",phone:"+225 07 08 12 34 56",product:"Offre Pro",objection:"Prix",color:"#376fcf"},
{id:2,name:"Fatou Ndiaye",initials:"FN",preview:"🎤 Message vocal (0:18)",time:"10:31",unread:1,status:"Très chaud",score:86,country:"Sénégal",phone:"+221 77 245 89 12",product:"Pack E-commerce",objection:"Confiance",color:"#b25b7d"},
{id:3,name:"Oumar Sawadogo",initials:"OS",preview:"Je vais comparer avec une autre...",time:"10:16",status:"Chaud",score:79,country:"Burkina Faso",phone:"+226 70 42 18 96",product:"Offre Starter",objection:"Comparaison",color:"#8759b7"},
{id:4,name:"Sarah Dubois",initials:"SD",preview:"Merci pour ces informations.",time:"09:48",status:"Intéressé",score:68,country:"France",phone:"+33 6 12 45 78 99",product:"Offre Pro",objection:"Timing",color:"#3f9c81"},
{id:5,name:"Marc Bamba",initials:"MB",preview:"Je veux parler à un conseiller.",time:"09:22",status:"Intervention",score:64,country:"Côte d’Ivoire",phone:"+225 05 16 72 45",product:"Business",objection:"Autre",color:"#d37b40"},
{id:6,name:"Aminata Diallo",initials:"AD",preview:"Le paiement est-il sécurisé ?",time:"Hier",status:"Intéressé",score:57,country:"Guinée",phone:"+224 621 45 89 70",product:"Offre Pro",objection:"Confiance",color:"#4b87aa"},
{id:7,name:"Paul Martin",initials:"PM",preview:"Je reviendrai le mois prochain.",time:"Hier",status:"À relancer",score:48,country:"Belgique",phone:"+32 479 12 34 56",product:"Starter",objection:"Timing",color:"#68759f"},
];
const filters=["Tous","Nouveaux","Intéressés","Chauds","À relancer","Clients","Intervention"];
export default function InboxPage(){
 const [selected,setSelected]=useState(conversations[0]);const [filter,setFilter]=useState("Tous");const [search,setSearch]=useState("");const [draft,setDraft]=useState("");const [length,setLength]=useState("normale");const [generating,setGenerating]=useState(false);const [toast,setToast]=useState("");const [showDetails,setShowDetails]=useState(false);
 const shown=conversations.filter(c=>(filter==="Tous"||(filter==="Chauds"&&c.score>=61)||c.status.includes(filter.replace("Nouveaux","Nouveau")))&&c.name.toLowerCase().includes(search.toLowerCase()));
 async function generate(){setGenerating(true);try{const r=await fetch("/api/ai/respond",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contact:selected.name,length,messages:[{role:"prospect",content:"Oui, l’offre me semble intéressante, mais 99 € c’est un peu cher pour moi."}],product:{name:selected.product,price:"99 €",benefits:["Assistant IA 24/7","Réponses vocales","2 500 conversations"]}})});const d=await r.json();setDraft(d.response||"Je comprends, le budget est un point important. Souhaitez-vous qu’on regarde ensemble si l’offre peut être rentabilisée selon votre volume de conversations ?");}catch{setDraft("Je comprends, le budget est un point important. Souhaitez-vous qu’on regarde ensemble si l’offre peut être rentabilisée selon votre volume de conversations ?");}finally{setGenerating(false)}}
 function notify(s:string){setToast(s);setTimeout(()=>setToast(""),2200)}
 return <div className={`inbox-shell ${showDetails?"details-open":""}`}>
  <aside className="conversation-list"><div className="conversation-tools"><div className="search-box"><Search/><input placeholder="Rechercher une conversation" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filter-scroll">{filters.map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}{f==="Intervention"&&<i>3</i>}</button>)}</div></div><div className="conversation-items">{shown.map(c=><button className={`conversation-item ${selected.id===c.id?"active":""}`} key={c.id} onClick={()=>{setSelected(c);setShowDetails(false)}}><span className="conv-avatar" style={{background:c.color}}>{c.initials}<i/></span><div className="conv-copy"><div><b>{c.name}</b><time>{c.time}</time></div><p className={c.preview.includes("vocal")?"voice-preview":""}>{c.preview}</p><div><span className={c.score>=81?"hot":""}>{c.status}</span><em>Score {c.score}</em></div></div>{c.unread&&<span className="unread">{c.unread}</span>}</button>)}</div></aside>
  <section className="chat-panel"><header className="chat-header"><button className="mobile-back" onClick={()=>setSelected(conversations[0])}>‹</button><span className="conv-avatar" style={{background:selected.color}}>{selected.initials}<i/></span><div><b>{selected.name}</b><small>En ligne · <span className="hot-dot"/> {selected.status} · Score {selected.score}</small></div><div className="chat-actions"><button className="icon-btn"><Phone/></button><button className="icon-btn" onClick={()=>setShowDetails(!showDetails)}><Info/></button><button className="icon-btn"><MoreHorizontal/></button></div></header>
   <div className="chat-messages"><div className="date-separator"><span>AUJOURD’HUI</span></div><Message side="in" time="10:35">Bonjour, je voudrais en savoir plus sur votre offre Pro. Est-ce qu’elle fonctionne avec mon numéro WhatsApp actuel ?</Message><div className="ai-event"><Bot/> CloseAI a détecté : <span>Intention d’achat</span><span>Intérêt élevé</span></div><Message side="out" time="10:36" ai>Bonjour Jean ! Oui, vous pouvez connecter votre numéro WhatsApp Business actuel via l’API officielle de Meta. Vos clients continueront à utiliser le même numéro. Gérez-vous déjà beaucoup de conversations par jour ?</Message><Message side="in" time="10:39">Environ 40 à 60 par jour. L’IA peut aussi répondre aux vocaux ?</Message><Message side="out" time="10:39" ai>Absolument. Lorsqu’un prospect vous envoie un vocal, CloseAI le transcrit, comprend sa demande puis lui répond avec un message vocal naturel, dans la langue et le ton que vous choisissez.</Message><Message side="in" time="10:42">Oui, ça semble intéressant, mais 99 € c’est un peu cher pour moi.</Message><div className="ai-event objection"><Sparkles/> Objection détectée : <b>Prix</b> · Intérêt toujours élevé <span>92/100</span></div>
   </div>
   <div className="composer-area">{draft&&<div className="ai-draft"><div className="draft-head"><span><WandSparkles/> Réponse suggérée par CloseAI</span><div><button title="Copier" onClick={()=>{navigator.clipboard?.writeText(draft);notify("Réponse copiée")}}><Copy/></button><button title="Régénérer" onClick={generate}><RefreshCw/></button><button title="Fermer" onClick={()=>setDraft("")}><X/></button></div></div><textarea value={draft} onChange={e=>setDraft(e.target.value)}/><div className="draft-actions"><span><ShieldCheckMini/> Conforme à votre base de connaissances</span><div><button className="btn btn-secondary btn-sm" onClick={()=>notify("Modification activée")}><Edit3/> Modifier</button><button className="btn btn-primary btn-sm" onClick={()=>{notify("Message envoyé en mode démo");setDraft("")}}><Send/> Envoyer</button></div></div></div>}
    {!draft&&<div className="generate-bar"><button className="generate-button" disabled={generating} onClick={generate}>{generating?<span className="spinner blue"/>:<WandSparkles/>}{generating?"Génération en cours...":"Générer une réponse"}</button><div className="length-select"><select value={length} onChange={e=>setLength(e.target.value)}><option value="courte">Courte</option><option value="normale">Normale</option><option value="détaillée">Détaillée</option></select><ChevronDown/></div></div>}
    <div className="message-input"><button><Paperclip/></button><input placeholder="Écrivez un message..."/><button className="voice-send"><Volume2/></button><button className="send-button"><Send/></button></div><div className="composer-meta"><span><Bot/> Mode Copilote — vous validez avant envoi</span><small>Entrée pour envoyer · Maj + Entrée pour une ligne</small></div>
   </div>
  </section>
  <aside className="prospect-panel"><div className="prospect-scroll"><button className="details-close" onClick={()=>setShowDetails(false)}><X/></button><div className="prospect-profile"><span className="large-avatar" style={{background:selected.color}}>{selected.initials}</span><h3>{selected.name}</h3><p>{selected.phone}</p><span className="badge badge-green"><i/>{selected.status}</span></div><div className="prospect-score"><div><span>Score commercial</span><small>Indicateur interne estimé</small></div><div className="score-ring" style={{"--score":`${selected.score*3.6}deg`} as React.CSSProperties}><span>{selected.score}</span></div></div><ProspectSection title="Analyse IA"><InfoRow label="Intention" value="Achat" tone="green"/><InfoRow label="Niveau d’intérêt" value={selected.status} tone="red"/><InfoRow label="Objection" value={selected.objection} tone="amber"/><InfoRow label="Sentiment" value="Positif" tone="blue"/><InfoRow label="Urgence" value="Moyenne"/></ProspectSection><ProspectSection title="Informations"><InfoRow label="Pays" value={selected.country}/><InfoRow label="Produit" value={selected.product}/><InfoRow label="Source" value="Campagne Instagram"/><InfoRow label="Première interaction" value="Aujourd’hui, 10:35"/></ProspectSection><div className="recommended-action"><Sparkles/><div><small>PROCHAINE ACTION</small><b>Traiter l’objection prix en valorisant le retour sur investissement.</b></div></div><ProspectSection title="Notes"><div className="note"><p>Gère entre 40 et 60 conversations par jour. Potentiel élevé.</p><small>Ajoutée par CloseAI · 10:41</small></div><button className="add-note">+ Ajouter une note</button></ProspectSection><div className="human-handoff"><button className="btn btn-secondary"><UserRound/> Transférer à un humain</button><button className="btn btn-ghost"><Archive/> Archiver</button></div></div></aside>
  {toast&&<div className="toast">{toast}</div>}
 </div>}
function Message({children,side,time,ai}:{children:React.ReactNode;side:"in"|"out";time:string;ai?:boolean}){return <div className={`app-message ${side}`}><div className="message-bubble">{ai&&<span className="ai-label"><Bot/> CloseAI</span>}<p>{children}</p><small>{time}{side==="out"&&<Check/>}</small></div></div>}
function ProspectSection({title,children}:{title:string;children:React.ReactNode}){return <section className="prospect-section"><h4>{title}</h4>{children}</section>}
function InfoRow({label,value,tone}:{label:string;value:string;tone?:string}){return <div className="info-row"><span>{label}</span><b className={tone||""}>{tone&&<i/>}{value}</b></div>}
function ShieldCheckMini(){return <Check/>}
