import { NextRequest, NextResponse } from "next/server";
import crypto from "node:crypto";
import { createServiceClient } from "@/lib/supabase/server";
import { generateCommercialResponse, synthesizeSpeech, transcribeAudio } from "@/lib/ai/orchestrator";
import { getMedia, markRead, sendAudio, sendText, uploadMedia } from "@/lib/whatsapp/client";

export const runtime="nodejs";
export const maxDuration=60;

type MetaMessage={id:string;from:string;timestamp:string;type:"text"|"audio"|"image"|string;text?:{body:string};audio?:{id:string;mime_type?:string};image?:{id:string;mime_type?:string;caption?:string}};
export async function GET(req:NextRequest){const p=req.nextUrl.searchParams;const mode=p.get("hub.mode"),token=p.get("hub.verify_token"),challenge=p.get("hub.challenge");if(mode==="subscribe"&&token&&token===process.env.META_WHATSAPP_VERIFY_TOKEN)return new NextResponse(challenge,{status:200});return NextResponse.json({error:"Webhook verification failed"},{status:403})}
export async function POST(req:NextRequest){
 const raw=await req.text();
 if(!validSignature(raw,req.headers.get("x-hub-signature-256"))){console.warn("WhatsApp webhook rejected: invalid signature");return NextResponse.json({error:"Invalid signature"},{status:401})}
 let body:any;try{body=JSON.parse(raw)}catch{console.warn("WhatsApp webhook rejected: invalid JSON");return NextResponse.json({error:"Invalid JSON"},{status:400})}
 if(body.object!=="whatsapp_business_account")return NextResponse.json({received:true});
  const jobs:Promise<void>[]=[];const fields=new Set<string>();
  for(const entry of body.entry||[])for(const change of entry.changes||[]){fields.add(String(change.field||"unknown"));const value=change.value||{};const phoneId=value.metadata?.phone_number_id;const profileName=value.contacts?.[0]?.profile?.name;for(const msg of value.messages||[])if(phoneId)jobs.push(handleMessage(phoneId,msg,profileName));}
  console.info("WhatsApp webhook accepted",{fields:[...fields],messageCount:jobs.length});
  if(jobs.length){
    const results=await Promise.allSettled(jobs);
    const failures=results.filter(result=>result.status==="rejected").length;
    if(failures)console.error("WhatsApp webhook jobs failed",{failures,total:results.length});
  }
 return NextResponse.json({received:true});
}

function validSignature(raw:string,signature:string|null){const secret=process.env.META_APP_SECRET;if(!secret)return process.env.NODE_ENV!=="production";if(!signature)return false;const digest="sha256="+crypto.createHmac("sha256",secret).update(raw).digest("hex");try{return crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(digest))}catch{return false}}
async function handleMessage(phoneId:string,msg:MetaMessage,profileName?:string){try{console.info("WhatsApp message processing started",{phoneId,type:msg.type,messageIdSuffix:msg.id?.slice(-8)});await markRead(phoneId,msg.id).catch((error)=>console.warn("WhatsApp mark-read failed",safeError(error)));const db=createServiceClient();let organizationId:string|undefined,accountId:string|undefined,auto=process.env.WHATSAPP_DEFAULT_MODE==="automatic";
 if(db){const {data:account}=await db.from("whatsapp_accounts").select("id, organization_id, mode, is_active").eq("phone_number_id",phoneId).eq("is_active",true).maybeSingle();if(account){organizationId=account.organization_id;accountId=account.id;auto=account.mode==="automatic"}}
 let content="",mediaMime:string|undefined,mediaId:string|undefined;
 if(msg.type==="text")content=msg.text?.body||"";
 else if(msg.type==="audio"&&msg.audio?.id){mediaId=msg.audio.id;const media=await getMedia(mediaId);mediaMime=media.mime;content=await transcribeAudio(media.bytes,media.mime)}
 else if(msg.type==="image"&&msg.image?.id){mediaId=msg.image.id;const media=await getMedia(mediaId);mediaMime=media.mime;content=await describeImage(media.bytes,media.mime,msg.image.caption)}
 else return;
 let conversationId:string|undefined;let history:{role:string;content:string}[]=[];let product:any;let knowledge:string[]=[];
  if(db&&organizationId){const {data:existing,error:existingError}=await db.from("messages").select("id").eq("external_id",msg.id).maybeSingle();if(existingError)throw existingError;if(existing){console.info("WhatsApp duplicate message ignored",{phoneId,messageIdSuffix:msg.id?.slice(-8)});return}const {data:contact,error:contactError}=await db.from("contacts").upsert({organization_id:organizationId,phone:msg.from,name:profileName||msg.from,last_interaction_at:new Date().toISOString()},{onConflict:"organization_id,phone"}).select("id").single();if(contactError||!contact)throw contactError||new Error("Contact could not be created");let {data:conv,error:convError}=await db.from("conversations").select("id,status").eq("organization_id",organizationId).eq("contact_id",contact.id).in("status",["open","human_required"]).order("created_at",{ascending:false}).limit(1).maybeSingle();if(convError)throw convError;if(!conv){const created=await db.from("conversations").insert({organization_id:organizationId,contact_id:contact.id,whatsapp_account_id:accountId,status:"open",channel:msg.type}).select("id,status").single();if(created.error||!created.data)throw created.error||new Error("Conversation could not be created");conv=created.data}conversationId=conv.id;const inbound=await db.from("messages").insert({organization_id:organizationId,conversation_id:conversationId,direction:"inbound",type:msg.type,content,external_id:msg.id,media_id:mediaId,media_mime:mediaMime,sent_at:new Date(Number(msg.timestamp)*1000).toISOString()}).select("id").single();if(inbound.error){if(inbound.error.code==="23505"){console.info("WhatsApp duplicate message ignored after race",{phoneId,messageIdSuffix:msg.id?.slice(-8)});return}throw inbound.error}const {data:past}=await db.from("messages").select("direction,content").eq("conversation_id",conversationId).order("sent_at",{ascending:false}).limit(20);history=(past||[]).reverse().map(m=>({role:m.direction==="inbound"?"prospect":"assistant",content:m.content||""}));const {data:products}=await db.from("products").select("name,description,price,currency,benefits,payment_link").eq("organization_id",organizationId).eq("is_active",true).limit(1);if(products?.[0])product={name:products[0].name,description:products[0].description,price:`${products[0].price} ${products[0].currency}`,benefits:products[0].benefits,paymentLink:products[0].payment_link};const {data:kb}=await db.from("knowledge_base").select("title,content").eq("organization_id",organizationId).eq("is_active",true).limit(8);knowledge=(kb||[]).map(k=>`${k.title}: ${k.content}`).filter(Boolean)}else history=[{role:"prospect",content}];
 const result=await generateCommercialResponse({contact:profileName,messages:history,product,knowledge,tone:"chaleureux et professionnel"});
 if(db&&organizationId&&conversationId){await db.from("conversations").update({intent:result.analysis.intent,interest_level:result.analysis.interest,objection:result.analysis.objection,sentiment:result.analysis.sentiment,urgency:result.analysis.urgency,lead_score:result.analysis.score,next_action:result.analysis.nextAction,status:result.analysis.requiresHuman?"human_required":"open",updated_at:new Date().toISOString()}).eq("id",conversationId);await db.from("objections").insert(result.analysis.objection?{organization_id:organizationId,conversation_id:conversationId,type:result.analysis.objection,source_message_id:msg.id}:[])}
 if(!auto){console.warn("WhatsApp automatic response skipped: mode is not automatic",{phoneId});return}
 if(result.analysis.requiresHuman)console.info("WhatsApp safe acknowledgement sent before human handoff",{phoneId,type:msg.type});
  if(msg.type==="audio"){try{const speech=await synthesizeSpeech(result.response);const outMediaId=await uploadMedia(phoneId,speech.bytes,speech.mime);await sendAudio(phoneId,msg.from,outMediaId,speech.mime.startsWith("audio/ogg"));console.info("WhatsApp audio response sent",{phoneId,mime:speech.mime,voiceNote:speech.mime.startsWith("audio/ogg")});if(db&&organizationId&&conversationId)await db.from("messages").insert({organization_id:organizationId,conversation_id:conversationId,direction:"outbound",type:"audio",content:result.response,media_id:outMediaId,media_mime:speech.mime,ai_generated:true,sent_at:new Date().toISOString()})}catch(error){console.warn("WhatsApp voice response unavailable, sending text fallback",{phoneId,error:safeError(error)});const out=await sendText(phoneId,msg.from,result.response);if(db&&organizationId&&conversationId)await db.from("messages").insert({organization_id:organizationId,conversation_id:conversationId,direction:"outbound",type:"text",content:result.response,external_id:out.messages?.[0]?.id,ai_generated:true,sent_at:new Date().toISOString()})}}
 else{const out=await sendText(phoneId,msg.from,result.response);console.info("WhatsApp text response sent",{phoneId});if(db&&organizationId&&conversationId)await db.from("messages").insert({organization_id:organizationId,conversation_id:conversationId,direction:"outbound",type:"text",content:result.response,external_id:out.messages?.[0]?.id,ai_generated:true,sent_at:new Date().toISOString()})}
 }catch(error){console.error("WhatsApp message processing failed",safeError(error))}}

function safeError(error:unknown){const message=error instanceof Error?error.message:String(error);return {name:error instanceof Error?error.name:"Error",message:message.replace(/Bearer\s+[A-Za-z0-9._-]+/gi,"Bearer [redacted]").slice(0,700)}}

async function describeImage(bytes:ArrayBuffer,mime:string,caption?:string){const key=process.env.OPENAI_API_KEY;if(!key)return `Le prospect a envoyé une image${caption?` avec la légende : ${caption}`:""}. L’image doit être examinée par un humain.`;const data=Buffer.from(bytes).toString("base64");const r=await fetch(`${process.env.OPENAI_BASE_URL||"https://api.openai.com/v1"}/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_VISION_MODEL||"gpt-4o-mini",messages:[{role:"system",content:"Décris factuellement cette image dans le contexte d'une conversation commerciale. S'il peut s'agir d'une preuve de paiement, précise qu'elle doit être vérifiée par un humain ou le fournisseur de paiement et ne la confirme jamais comme définitive."},{role:"user",content:[{type:"text",text:caption||"Analyse cette image."},{type:"image_url",image_url:{url:`data:${mime};base64,${data}`}}]}],max_tokens:350})});if(!r.ok)throw new Error(`Vision ${r.status}`);const j=await r.json();return String(j.choices?.[0]?.message?.content||"Image reçue à vérifier.")}
