const API_VERSION=process.env.META_GRAPH_API_VERSION||"v22.0";
const BASE=`https://graph.facebook.com/${API_VERSION}`;
function token(){const value=process.env.META_WHATSAPP_ACCESS_TOKEN;if(!value)throw new Error("META_WHATSAPP_ACCESS_TOKEN is missing");return value}
export async function getMedia(mediaId:string){const info=await fetch(`${BASE}/${mediaId}`,{headers:{Authorization:`Bearer ${token()}`}});if(!info.ok)throw new Error(`Meta media info ${info.status}`);const data=await info.json();const media=await fetch(data.url,{headers:{Authorization:`Bearer ${token()}`}});if(!media.ok)throw new Error(`Meta media download ${media.status}`);return {bytes:await media.arrayBuffer(),mime:String(media.headers.get("content-type")||data.mime_type||"application/octet-stream")}}
export async function sendText(phoneNumberId:string,to:string,text:string){return sendMessage(phoneNumberId,{messaging_product:"whatsapp",recipient_type:"individual",to,type:"text",text:{preview_url:false,body:text}})}
export async function uploadMedia(phoneNumberId:string,bytes:ArrayBuffer,mime="audio/ogg"){const form=new FormData();const extension=mime.includes("mpeg")||mime.includes("mp3")?"mp3":mime.includes("mp4")?"mp4":mime.includes("aac")?"aac":"ogg";form.append("messaging_product","whatsapp");form.append("type",mime);form.append("file",new Blob([bytes],{type:mime}),`reply.${extension}`);const r=await fetch(`${BASE}/${phoneNumberId}/media`,{method:"POST",headers:{Authorization:`Bearer ${token()}`},body:form});if(!r.ok)throw new Error(`Meta media upload ${r.status}: ${await r.text()}`);return (await r.json()).id as string}
export async function sendAudio(phoneNumberId:string,to:string,mediaId:string){return sendMessage(phoneNumberId,{messaging_product:"whatsapp",recipient_type:"individual",to,type:"audio",audio:{id:mediaId}})}
export async function markRead(phoneNumberId:string,messageId:string){return sendMessage(phoneNumberId,{messaging_product:"whatsapp",status:"read",message_id:messageId})}
async function sendMessage(phoneNumberId:string,payload:unknown){const r=await fetch(`${BASE}/${phoneNumberId}/messages`,{method:"POST",headers:{Authorization:`Bearer ${token()}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error(`Meta message ${r.status}: ${await r.text()}`);return r.json()}
